build_targets:
- commands:
  - ./scripts/downloadDependencies.sh
  container:
    image: yourbase/yb_ubuntu:18.04
  name: default
  environment:
      - JAVA_TOOL_OPTIONS="-Xms64m -Xmx250m"
      - GRADLE_OPTS='-Dorg.gradle.jvmargs="-Xms64m -Xmx250m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'
      - TERM=dumb

ci:
  builds:
  - build_target: default
    name: default
dependencies:
  build:
  - java:11.0.6
  - maven:3.6.3
