build_targets:
- commands:
  - ./scripts/downloadDependencies.sh
  - rm -rf ~/.m2/repository/org/springframework/cloud/contract
  - rm -rf ~/.m2/repository/com/example
  - ./scripts/ciBuild.sh
  container:
    image: yourbase/yb_ubuntu:18.04
  name: default
  environment:
      - GRADLE_OPTS='-Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'
      - TERM=dumb

ci:
  builds:
  - build_target: default
    name: default
dependencies:
  build:
  - java:11.0.6
  - maven:3.6.3
